GET http://localhost:8000/users
accept: application/json

###

POST http://localhost:8000/users
accept: application/json
content-type: application/json

{
    "email": "person1@email.comx",
    "password": "pwd4_person1"
}

###

GET http://localhost:8000/users/1
accept: application/json

###

GET http://localhost:8000/items
accept: application/json

###

POST http://localhost:8000/users/1/items
accept: application/json
content-type: application/json

{
    "title": "Plumbus",
    "description": "Everyone knows what a plumbus is"
}
