GET http://localhost:8000/users
accept: application/json

###

POST http://localhost:8000/users
accept: application/json
content-type: application/json

{
    "email": "person2@email.comx",
    "password": "pwd4_person2"
}

###

GET http://localhost:8000/users/1
accept: application/json

###

GET http://localhost:8000/items
accept: application/json

###

POST http://localhost:8000/users/2/items
accept: application/json
content-type: application/json

{
    "title": "Person 2 Item",
    "description": "Item 2 Description"
}
